### ISSUE TITLE
Allow the removal of submissions by their owners

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot-showreel-voting#17]
Some users got in touch with us asking to remove the game from the submission list. It would be good to have that functionality available for them.

**Comment by N3ST0R-byte** [comment]
Currently, users can delete entries only when the showreel is open for submissions. To enable deletion during the voting phase, a quick solution would be to include `or Showreel.VOTE` on [line 164 of views.py](https://github.com/godotengine/godot-showreel-voting/blob/master/vote/views.py#L164). However, I'm unsure if this aligns with the intended functionality, especially if deletion should only be allowed when the submissions is open.
